version: '3.8'

services:
  pgsql:
    container_name: sc-pgsql
    image: postgres:latest
    env_file:
      - .env.database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - supercars-network

  server:
    container_name: sc-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/:/server/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env.server
    ports:
      - 8000:8000
    networks:
      - supercars-network
    depends_on:
      - pgsql

  web:
    container_name: sc-web
    build:
      context: ./web
      dockerfile: Dockerfile

    # Set envrionment variables based on the .env file
    env_file:
      - .env.web
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - supercars-network
    depends_on:
      - server

networks:
  supercars-network:
    external: true
