version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/:/server/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./server/.env
    ports:
      - 8000:8000

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/:/web/
    command: yarn start
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - server
